spring.application.name=springboot

server.port = 8080
spring.datasource.url=jdbc:oracle:thin:@192.168.0.43:1521/XE
spring.datasource.username=fourjo
spring.datasource.password=4444
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
mybatis.configuration.map-underscore-to-camel-case=true
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
app.python-exec=C:/Users/human-16/AppData/Local/Programs/Python/Python311/python.exe
app.base-dir=C:/MedNeuro/backend/4project
app.python-slice-script=${app.base-dir}/python/save_slice_2d.py
app.python-obj-script=${app.base-dir}/python/save_obj_3d.py

app.upload-dir=${app.base-dir}/data/uploads
app.output-slice-dir=${app.base-dir}/data/outputs/slices
app.output-obj-dir=${app.base-dir}/data/outputs/obj
