# -*- coding: utf-8 -*-
"""
✅ save_obj_3d.py
"""

import argparse
import json
import numpy as np
import nibabel as nib
from skimage import measure
from typing import Optional

def pick_volume(data: np.ndarray) -> np.ndarray:
    if data.ndim == 3:
        return data
    if data.ndim == 4:
        return data[:, :, :, 0]
    raise ValueError(f"Unsupported NIfTI dimension: {data.ndim}")


def write_obj(path: str, verts: np.ndarray, faces: np.ndarray, normals: Optional[np.ndarray] = None):
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by save_obj_3d.py\n")

        for v in verts:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")

        if normals is not None:
            for n in normals:
                f.write(f"vn {n[0]} {n[1]} {n[2]}\n")

        for face in faces:
            a, b, c = face + 1
            if normals is not None:
                f.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")
            else:
                f.write(f"f {a} {b} {c}\n")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    nii = nib.load(args.input)
    data = nii.get_fdata()
    vol = pick_volume(data).astype(np.float32)
    vol = np.nan_to_num(vol, nan=0.0, posinf=0.0, neginf=0.0)

    level = float(np.percentile(vol, 70))
    verts, faces, normals, _ = measure.marching_cubes(vol, level=level)

    write_obj(args.out, verts, faces, normals)

    print(json.dumps({
        "ok": True,
        "out": args.out,
        "level": level,
        "vertexCount": int(verts.shape[0]),
        "faceCount": int(faces.shape[0])
    }, ensure_ascii=False))

if __name__ == "__main__":
    main()
