# -*- coding: utf-8 -*-
"""
✅ save_obj_3d.py
- Otsu Thresholding ( 자동 영역 분할)
- Morphology (노이지 제거)
- Gaussian Smoothing (표면 부드럽게..

"""

import argparse
import json
import numpy as np
import nibabel as nib
from skimage import measure, morphology, filters
from scipy.ndimage import gaussian_filter
from skimage.measure import label as cc_label, regionprops
from typing import Optional

def pick_volume(data: np.ndarray) -> np.ndarray:
    # 4차원 데이터를 3차원 으로 축소..
    if data.ndim == 3:
        return data
    if data.ndim == 4:
        return data[:, :, :, 0]
    raise ValueError(f"Unsupported NIfTI dimension: {data.ndim}")

def get_brain_mask(img3d):
    """" Otsu 알고리즘 + 모폴로지 연산으로 뇌 영역만 깔끔하게 추출 """
    # 1. 정규화 (0~1 사이 값으로 변환)
    # 상위 1%와 하위 1% 밝기를 기준으로 잡음 제거
    p1 = np.percentile(img3d, 1)
    p99 = np.percentile(img3d, 99)
    x = np.clip((img3d - p1) / (p99 - p1 + 1e-6),0,1)

    # 2. Otsu 임계값 자동 계산 (배경과 물체를 나누는 최적의 선)
    t = filters.threshold_otsu(x) * 0.9 # 0.9는 약간 여유를 둠
    mask = x > t

    # 3. 노이즈 제거 (모폴로지 연산)
    # 작은 점들을 없애고(Opening), 구멍을 메움(Closing)
    mask = morphology.binary_opening(mask, morphology.ball(1))
    mask = morphology.binary_opening(mask, morphology.ball(2))

    # 4. 가장 큰 덩어리만 남기기 (허공에 떠있는 작은 노이즈 삭제)
    lab = cc_label(mask)
    if lab.max() == 0:
        return mask

    # 영역들의 크기를 계산해서 가장 큰 것 하나만 선택
    regions = regionprops(lab)
    regions.sort(key=lambda r: r.area, reverse=True)
    mask = (lab == regions[0].label)

    return mask


def write_obj(path: str, verts: np.ndarray, faces: np.ndarray, normals: Optional[np.ndarray] = None):
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by save_obj_3d.py\n")

        for v in verts:
            f.write(f"v {v[0]:.4f} {v[1]:.4f} {v[2]:.4f}\n")

        if normals is not None:
            for n in normals:
                f.write(f"vn {n[0]:.4f} {n[1]:.4f} {n[2]:.4f}\n")

        for face in faces:
            a, b, c = face + 1
            if normals is not None:
                f.write(f"f {a}//{a} {b}//{b} {c}//{c}\n")
            else:
                f.write(f"f {a} {b} {c}\n")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--out", required=True)
    # 부드러움 정도 조절 ( 기본값 1.0, 높을수록 뭉개짐)
    parser.add_argument("--sigma", type=float, default=1.0)
    args = parser.parse_args()

    # 1. 파일 로드
    nii = nib.load(args.input)
    data = nii.get_fdata()
    vol = pick_volume(data).astype(np.float32)
    vol = np.nan_to_num(vol, nan=0.0, posinf=0.0, neginf=0.0)

    # 2. [개선] 뇌 영역 마스크 추출 (잡티 제거)
    mask = get_brain_mask(vol)

    # 마스크가 씌워진 데이터만 남김 ( 배경은 0으로)
    vol_masked = np.zeros_like(vol)
    vol_masked[mask] = vol[mask]

    # 3. [개선] 스무딩
    # 매쉬를 만들기 전에 3D 볼륨 자체를 살짝 흐리게 하면 표면이 매우 매끄러워짐
    # sigma 값이 클수록 더 부드러워짐 ( 보통 0.5 ~ 1.5 사용)
    vol_smooth = gaussian_filter(vol_masked, sigma=args.sigma)

    # 4. Marching Cubes (3D 모델 생성
    # 스무딩된 데이터에서 0.0 보다 큰 영역의 경계면 추출
    try:
        # level을 아주 낮은 값(예: Otsu결과의 절반)이나 0 근처로 잡음
        verts, faces, normals, _ = measure.marching_cubes(vol_smooth, level=0.1)

        # 5. OBJ 저장
        write_obj(args.out, verts, faces, normals)

        print(json.dumps({
            "ok": True,
            "out": args.out,
            "vertexCount": int(verts.shape[0]),
            "faceCount": int(faces.shape[0])
        }, ensure_ascii=False))

    except Exception as e:
        # 모델 생성 실패 시 에러 JSON 출력
        print(json.dumps({
            "ok": False,
            "error": str(e)
        }, ensure_ascii=False))

if __name__ == "__main__":
    main()
