-- [1] MEDICAL_STAFF (의료진)
-- PK인 STAFF_ID는 자동 생성됨
CREATE INDEX IX_STAFF_ACCOUNT_ID ON MEDICAL_STAFF(ACCOUNT_ID);
CREATE INDEX IX_STAFF_DEPT_CODE ON MEDICAL_STAFF(DEPT_ID);
CREATE INDEX IX_STAFF_RANK_CODE ON MEDICAL_STAFF(RANK_ID); -- 직급 코드로 조회할 경우 대비

-- [2] PATIENT (환자)
-- PK인 PATIENT_ID는 자동 생성됨
CREATE INDEX IX_PATIENT_ACCOUNT_ID ON PATIENT(ACCOUNT_ID);

-- [3] SYSTEM_LOG (로그)
-- PK인 LOG_ID는 자동 생성됨
CREATE INDEX IX_LOG_ACCOUNT_ID ON SYSTEM_LOG(ACCOUNT_ID);

-- [4] BRAIN_MRI_FOLDER (MRI 폴더)
-- PK인 MRI_ID는 자동 생성됨
CREATE INDEX IX_MRI_PATIENT_ID ON MEDICAL_MRI_FOLDER(PATIENT_ID);
CREATE INDEX IX_MRI_DOCTOR_ID ON MEDICAL_MRI_FOLDER(DOCTOR_ID);

-- [5] DIAGNOSIS_REPORT (판독지)
-- PK인 REPORT_ID는 자동 생성됨
CREATE INDEX IX_REPORT_MRI_ID ON DIAGNOSIS_REPORT(MED_MRI_ID);
CREATE INDEX IX_REPORT_WRITER_ID ON DIAGNOSIS_REPORT(WRITER_ID);

-- [6] TUMOR_ANNOTATION (종양 마킹)
-- PK인 ANNOT_ID는 자동 생성됨
CREATE INDEX IX_ANNOT_MRI_ID ON TUMOR_ANNOTATION(MED_MRI_ID);
CREATE INDEX IX_ANNOT_WRITER_ID ON TUMOR_ANNOTATION(WRITER_ACCOUNT_ID); -- 작성자 계정 ID

-- [참고] DEPARTMENT 테이블의 DEPT_CODE와
-- INTEGRATED_ACCOUNT 테이블의 ACCOUNT_ID는
-- 이미 PK라서 인덱스가 자동 생성되어 있습니다.



-- [1] 시퀀스 생성
CREATE SEQUENCE SEQ_INTEGRATED_ACCOUNT
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 999999
    MINVALUE 1
    CYCLE
    NOCACHE;

-- [2] 부모 테이블: DEPARTMENT (진료과)
CREATE TABLE DEPARTMENT (
                            DEPT_ID   VARCHAR2(10)  NOT NULL,
                            DEPT_NAME VARCHAR2(50)  NOT NULL,
                            CONSTRAINT PK_DEPARTMENT PRIMARY KEY (DEPT_ID)
);

-- [3] 부모 테이블: INTEGRATED_ACCOUNT (통합 계정)
CREATE TABLE INTEGRATED_ACCOUNT (
                                    ACCOUNT_ID      NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    LOGIN_ID        VARCHAR2(50)   NOT NULL,
                                    PASSWORD        VARCHAR2(255)  NOT NULL, -- 암호화된 비밀번호
                                    USER_TYPE       VARCHAR2(10)   NOT NULL,
                                    LAST_LOGIN_DATE DATE,
                                    JOIN_DATE       DATE           DEFAULT SYSDATE,
                                    CONSTRAINT UK_ACCOUNT_LOGIN_ID UNIQUE (LOGIN_ID)
);

-- [4] 자식 테이블: MEDICAL_STAFF (의료진)
CREATE TABLE MEDICAL_STAFF (
                               STAFF_ID     VARCHAR2(20)   NOT NULL,
                               ACCOUNT_ID   NUMBER,        -- ALTER 내용 반영: NULL 허용
                               DEPT_ID      VARCHAR2(10)   NOT NULL,
                               STAFF_NAME   VARCHAR2(50)   NOT NULL,
                               EMAIL        VARCHAR2(200), -- 암호화 대비 길이 확장
                               PHONE_NUMBER VARCHAR2(200),
                               GENDER         CHAR(1),
                               BIRTH_DATE     VARCHAR2(8),
                               JOB_TYPE     VARCHAR2(20),
                               RANK_ID      VARCHAR2(20),
                               LICENSE_NO   VARCHAR2(50),
                               CONSTRAINT PK_MEDICAL_STAFF PRIMARY KEY (STAFF_ID),
                               CONSTRAINT UK_STAFF_EMAIL UNIQUE (EMAIL),
                               CONSTRAINT UK_STAFF_PHONE UNIQUE (PHONE_NUMBER),
                               CONSTRAINT UK_STAFF_LICENSE UNIQUE (LICENSE_NO),
                               CONSTRAINT FK_STAFF_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
                                   REFERENCES INTEGRATED_ACCOUNT(ACCOUNT_ID),
                               CONSTRAINT FK_STAFF_DEPT FOREIGN KEY (DEPT_ID)
                                   REFERENCES DEPARTMENT(DEPT_ID)
);

-- 의료진 관련 인덱스
CREATE INDEX IX_STAFF_ACCOUNT_ID ON MEDICAL_STAFF(ACCOUNT_ID);
CREATE INDEX IX_STAFF_DEPT_CODE ON MEDICAL_STAFF(DEPT_ID);
CREATE INDEX IX_STAFF_RANK_CODE ON MEDICAL_STAFF(RANK_ID);
CREATE SEQUENCE SQ_STAFF_ID
    START WITH 1
    INCREMENT BY 1    MAXVALUE 999999
    MINVALUE 1
    NOCACHE;
CREATE TABLE GENERAL (
                         GENERAL_ID     VARCHAR2(20)   NOT NULL,
                         ACCOUNT_ID     NUMBER,        -- ALTER 내용 반영: NULL 허용
                         GENERAL_NAME   VARCHAR2(50)   NOT NULL,
                         EMAIL          VARCHAR2(200),
                         PHONE_NUMBER   VARCHAR2(200),
                         GENDER         CHAR(1),
                         BIRTH_DATE     VARCHAR2(8),
                         CONSTRAINT PK_GENERAL PRIMARY KEY (GENERAL_ID),
                         CONSTRAINT UK_GENERAL_EMAIL UNIQUE (EMAIL),
                         CONSTRAINT UK_GENERAL_PHONE_NUMBER UNIQUE (PHONE_NUMBER),
                         CONSTRAINT FK_GENERAL_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
                            REFERENCES INTEGRATED_ACCOUNT(ACCOUNT_ID)
);
CREATE INDEX IX_GENERAL_MATCHING ON GENERAL (GENERAL_NAME, PHONE_NUMBER, BIRTH_DATE, GENDER);
CREATE INDEX IX_GENERAL_EMAIL ON GENERAL (EMAIL);
CREATE SEQUENCE SEQ_GENERAL_MEMBER
    START WITH 1
    INCREMENT BY 1;
CREATE SEQUENCE SEQ_GENERAL_ID
    START WITH 1
    INCREMENT BY 1    MAXVALUE 999999
    MINVALUE 1
    CYCLE
    NOCACHE;
COMMIT;
-- [5] 자식 테이블: PATIENT (환자)
CREATE TABLE PATIENT (
                         PATIENT_ID     VARCHAR2(20)   NOT NULL,
                         ACCOUNT_ID     NUMBER,        -- ALTER 내용 반영: NULL 허용
                         PATIENT_NAME   VARCHAR2(50)   NOT NULL,
                         EMAIL          VARCHAR2(200),
                         PHONE_NUMBER   VARCHAR2(200),
                         SSN            VARCHAR2(500)  NOT NULL, -- ALTER 내용 반영: 길이 500
                         BLOOD_TYPE     VARCHAR2(5),
                         GENDER         CHAR(1),
                         BIRTH_DATE     VARCHAR2(8),
                         INSURANCE_TYPE VARCHAR2(20),
                         CONSTRAINT PK_PATIENT PRIMARY KEY (PATIENT_ID),
                         CONSTRAINT UK_PATIENT_EMAIL UNIQUE (EMAIL),
                         CONSTRAINT UK_PATIENT_SSN UNIQUE (SSN),
                         CONSTRAINT FK_PATIENT_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
                             REFERENCES INTEGRATED_ACCOUNT(ACCOUNT_ID)
);

-- 환자 관련 인덱스
CREATE INDEX IX_PATIENT_ACCOUNT_ID ON PATIENT(ACCOUNT_ID);
-- 복합 인덱스 (환자 검색용)
CREATE INDEX IX_PATIENT_MATCHING ON PATIENT (PATIENT_NAME, PHONE_NUMBER, BIRTH_DATE, GENDER);

-- [6] 로그 테이블: SYSTEM_LOG 통합 계정 전용 로그
-- 로그인/오류/계정관련 시스템 활동만 기록하는 로그 테이블.
CREATE TABLE SYSTEM_LOG (
                            LOG_ID        NUMBER        NOT NULL,
                            ACCOUNT_ID    NUMBER,
                            ACTION_TYPE   VARCHAR2(50),
        -- 로그인/접속(성공/실패/로그아웃) - 계정관리(비밀번호 변경/계정 잠김/ 회원 정보 수정) - 시스템 오류(예상치 못한 시스템 에러 발생 시)
                            IP_ADDR       VARCHAR2(40), -- ip 주소
                            LOG_DATE      DATE          DEFAULT SYSDATE,
                            CONSTRAINT PK_SYSTEM_LOG PRIMARY KEY (LOG_ID),
                            CONSTRAINT FK_LOG_ACCOUNT FOREIGN KEY (ACCOUNT_ID)
                                REFERENCES INTEGRATED_ACCOUNT(ACCOUNT_ID)
);

-- 로그 인덱스
CREATE INDEX IX_LOG_ACCOUNT_ID ON SYSTEM_LOG(ACCOUNT_ID);

commit;

-- ========================================================
-- [A] 의료진/환자 전용: MEDICAL_MRI_FOLDER
-- 특징: DOCTOR_ID(필수), PATIENT_ID(필수)
-- 용도: 실제 진료 및 정밀 판독용
-- ========================================================
-- [A] 의료진/환자 전용: MEDICAL_MRI_FOLDER
CREATE TABLE MEDICAL_MRI_FOLDER (
    -- 시퀀스 없이 여기서 한방에 해결!
                                    MED_MRI_ID              NUMBER         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    PATIENT_ID          VARCHAR2(20)   NOT NULL,
                                    DOCTOR_ID           VARCHAR2(20)   NOT NULL,
                                    IMAGE_FOLDER_PATH   VARCHAR2(255)  NOT NULL,
                                    UPLOAD_DT           DATE           DEFAULT SYSDATE,
                                    TOTAL_SLICES        NUMBER,
                                    AI_ANALYSIS_STATUS  VARCHAR2(20)   DEFAULT 'PENDING',
                                    AI_MODEL_VERSION    VARCHAR2(20),

                                    CONSTRAINT FK_MED_MRI_PATIENT FOREIGN KEY (PATIENT_ID)
                                        REFERENCES PATIENT(PATIENT_ID),
                                    CONSTRAINT FK_MED_MRI_DOCTOR FOREIGN KEY (DOCTOR_ID)
                                        REFERENCES MEDICAL_STAFF(STAFF_ID)
);
CREATE INDEX MD_MRI_DOCTOR_ID ON MEDICAL_MRI_FOLDER(DOCTOR_ID);
CREATE INDEX MD_MRI_GENERAL_ID ON MEDICAL_MRI_FOLDER(PATIENT_ID);
-- [B] 일반 사용자 전용: GENERAL_MRI_FOLDER
CREATE TABLE GENERAL_MRI_FOLDER (
    -- 여기도 IDENTITY 적용 (시작값 50000부터 하려면 옵션 추가 가능)
                                    GEN_MRI_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY
                                                    (START WITH 50000 INCREMENT BY 1) PRIMARY KEY,
                                    GENERAL_ID          VARCHAR2(20)   NOT NULL,
                                    IMAGE_FOLDER_PATH   VARCHAR2(255)  NOT NULL,
                                    UPLOAD_DT           DATE           DEFAULT SYSDATE,
                                    AI_ANALYSIS_STATUS  VARCHAR2(20)   DEFAULT 'PENDING',
                                    AI_RESULT_SUMMARY   VARCHAR2(500),

                                    CONSTRAINT FK_GEN_MRI_USER FOREIGN KEY (GENERAL_ID)
                                        REFERENCES GENERAL(GENERAL_ID)
);

-- 검색 성능을 위한 인덱스
CREATE INDEX GN_GEN_MRI_USER ON GENERAL_MRI_FOLDER(GENERAL_ID);

-- 일반용 시퀀스 따로 관리 (구분을 위해 50000번부터 시작 추천)
CREATE SEQUENCE SEQ_GENERAL_MRI_ID START WITH 50000 INCREMENT BY 1;

-- [7-1] 의사 최근 기록 테이블 : MRI_ACCESS_LOG // MRI 폴더 기록 테이블 // 의사,환자 전용임
CREATE TABLE MRI_ACCESS_LOG (
                                MRI_LOG_ID              NUMBER         GENERATED BY DEFAULT AS IDENTITY, -- 순번 자동 생성
                                MED_MRI_ID              NUMBER         NOT NULL,  -- 어떤 MRI를 봤는지
                                DOCTOR_ID           VARCHAR2(20), -- 누가 봤는지
                                ACCESS_DT            DATE           DEFAULT SYSDATE, -- 언제 봤는지 (자동입력)
                                CONSTRAINT PK_MRI_ACCESS_LOG PRIMARY KEY (MRI_LOG_ID),
                                CONSTRAINT FK_MED_MRI_ID FOREIGN KEY (MED_MRI_ID) REFERENCES MEDICAL_MRI_FOLDER(MED_MRI_ID),
                                CONSTRAINT FK_LOG_DOCTOR FOREIGN KEY (DOCTOR_ID) REFERENCES MEDICAL_STAFF(STAFF_ID)
                            );

CREATE INDEX IX_LOG_MRI_ID ON MRI_ACCESS_LOG(MED_MRI_ID);
CREATE INDEX IX_DOCTOR_ID ON MRI_ACCESS_LOG(DOCTOR_ID);


commit;


-- [8] 분석 테이블: DIAGNOSIS_REPORT // 판독지 /결과 리포트
CREATE TABLE DIAGNOSIS_REPORT (
                                  REPORT_ID   NUMBER         NOT NULL,
                                  MED_MRI_ID      NUMBER         NOT NULL,
                                  WRITER_ID   VARCHAR2(20)   NOT NULL,
                                  TUMOR_TYPE  VARCHAR2(100),
                                  FINDINGS    CLOB,
                                  CONCLUSION  CLOB,
                                  IS_FINAL    CHAR(1) DEFAULT 'N',
                                  CREATE_DATE DATE DEFAULT SYSDATE,
                                  UPDATE_DATE DATE,
                                  FINAL_DATE  DATE,
                                  CONSTRAINT PK_DIAGNOSIS_REPORT PRIMARY KEY (REPORT_ID),
                                  CONSTRAINT FK_REPORT_MRI FOREIGN KEY (MED_MRI_ID)
                                      REFERENCES MEDICAL_MRI_FOLDER(MED_MRI_ID), -- 의사 전용 테이블이기 때문에 일반 사용자 x
                                  CONSTRAINT FK_REPORT_WRITER FOREIGN KEY (WRITER_ID)
                                      REFERENCES MEDICAL_STAFF(STAFF_ID)
);
/*
TUMOR_TYPE -- 종양 타입 - 정형화된 진단명 (수막종/신경교종/교모세포종/뇌하수체 선종 등등)
FINDINGS -- 영상 소견서
CONCLUSION -- 결론 및 진단 내용
WRITER_ID -- 판독을 작성한 의사
IS_FINAL -- N - 판독지 작성종 / Y - 의사가 다 썼으며 환자가 조회 가능 및 수정이 불가!!
*/
-- 판독지 인덱스
CREATE INDEX IX_REPORT_MED_MRI_ID ON DIAGNOSIS_REPORT(MED_MRI_ID);
CREATE INDEX IX_REPORT_WRITER_ID ON DIAGNOSIS_REPORT(WRITER_ID);

-- [9] 마킹 테이블: TUMOR_ANNOTATION // 시각적 마킹! 즉, 그림 정보의 좌표 형태
CREATE TABLE TUMOR_ANNOTATION (
                                  ANNOT_ID          NUMBER        NOT NULL,
                                  MED_MRI_ID            NUMBER        NOT NULL,
                                  WRITER_ACCOUNT_ID NUMBER        NOT NULL,
                                  IMAGE_Z_INDEX     NUMBER,
                                  COORDINATE_JSON   CLOB,
                                  IS_AI_GENERATED   CHAR(1),
                                  CONFIDENCE_SCORE  NUMBER(5,4),
                                  CREATE_DATE       DATE DEFAULT SYSDATE,
                                  CONSTRAINT PK_TUMOR_ANNOTATION PRIMARY KEY (ANNOT_ID),
                                  CONSTRAINT FK_ANNOT_MRI FOREIGN KEY (MED_MRI_ID)
                                      REFERENCES MEDICAL_MRI_FOLDER(MED_MRI_ID), -- 의사가 마킹하기 때문에 패스.
                                  CONSTRAINT FK_ANNOT_WRITER FOREIGN KEY (WRITER_ACCOUNT_ID)
                                      REFERENCES INTEGRATED_ACCOUNT(ACCOUNT_ID)
);
/*
AI 또는 의사가 MRI 이미지의 특정 위치에 마킹한 정보를 저장하는 테이블!!
IMAGE_Z_INDEX -- 몇 번째 장
COORDINATE_JSON -- 어느 위치 (이건 JSON 파일이 아니라면 위치 정보 다르게 저장하면 됨) 추후 변경 예정
IS_AI_GENERATED -- Y/N으로 AI가 찾으면 Y  의사가 찾으면 N으로 AI가 그린 것인지 여부 확인
CONFIDENCE_SCORE -- AI의 확률 퍼센트지 98%일 경우 0.98
*/
-- 어노테이션 인덱스
CREATE INDEX IX_ANNOT_MRI_ID ON TUMOR_ANNOTATION(MED_MRI_ID);
CREATE INDEX IX_ANNOT_WRITER_ID ON TUMOR_ANNOTATION(WRITER_ACCOUNT_ID);

/*
- 수정 완료
ALTER TABLE MEDICAL_STAFF MODIFY(ACCOUNT_ID NUMBER NULL);
ALTER TABLE PATIENT MODIFY(ACCOUNT_ID NUMBER NULL);
ALTER TABLE PATIENT MODIFY (SSN VARCHAR2(500));
-- 문법: ALTER TABLE 테이블명 DROP CONSTRAINT 제약조건명;
ALTER TABLE PATIENT DROP CONSTRAINT UK_PATIENT_PHONE;

-- 문법: CREATE INDEX 인덱스명 ON 테이블명 (컬럼1, 컬럼2, ...);
CREATE INDEX IX_PATIENT_MATCHING
    ON PATIENT (PATIENT_NAME, PHONE_NUMBER, BIRTH_DATE, GENDER);

-- 오라클 기준: 해당 테이블의 제약조건 조회

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PATIENT';
*/
commit;
SELECT * FROM INTEGRATED_ACCOUNT;
SELECT * FROM PATIENT;
SELECT * FROM GENERAL;
SELECT * FROM MEDICAL_STAFF;
SELECT * FROM DEPARTMENT;
SELECT * FROM MEDICAL_MRI_FOLDER;
SELECT * FROM GENERAL_MRI_FOLDER;
SELECT * FROM MRI_ACCESS_LOG;



INSERT INTO PATIENT(PATIENT_ID,ACCOUNT_ID,PATIENT_NAME,EMAIL,PHONE_NUMBER,SSN,BLOOD_TYPE,GENDER,BIRTH_DATE,INSURANCE_TYPE)
VALUES (1,null,'홍길동','1111@gmail.com','010-1234-5678','20251217-1234567','rh+B','M','20251217',null);
INSERT INTO INTEGRATED_ACCOUNT VALUES (SEQ_INTEGRATED_ACCOUNT.NEXTVAL, 'testG', '1111', 'G', SYSDATE, SYSDATE);
INSERT INTO INTEGRATED_ACCOUNT VALUES (SEQ_INTEGRATED_ACCOUNT.NEXTVAL, 'testD', '2222', 'D', SYSDATE, SYSDATE);
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_NAME) VALUES (10,'내과');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_NAME) VALUES (20,'신경외과');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_NAME) VALUES (30,'신경과');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_NAME) VALUES (40,'영상의학과과');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_NAME) VALUES (50,'종양내과');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_NAME) VALUES (60,'병리과');
INSERT INTO PATIENT(PATIENT_ID,ACCOUNT_ID,PATIENT_NAME,EMAIL,PHONE_NUMBER,SSN,BLOOD_TYPE,GENDER,BIRTH_DATE,INSURANCE_TYPE)
VALUES (2,null,'변길동','11133@gmail.com','010-1234-1234','20251217-2345678','rh+B','M','20251218',null);

INSERT INTO MEDICAL_STAFF(STAFF_ID, ACCOUNT_ID, DEPT_ID, STAFF_NAME, EMAIL, PHONE_NUMBER, GENDER, BIRTH_DATE, JOB_TYPE, RANK_ID, LICENSE_NO)
VALUES(SQ_STAFF_ID.nextval,NULL,10,'김길동','1234@gmail.com','010-1111-2222','M','20251219','의사','과장','111111');
INSERT INTO MEDICAL_STAFF(STAFF_ID, ACCOUNT_ID, DEPT_ID, STAFF_NAME, EMAIL, PHONE_NUMBER, GENDER, BIRTH_DATE, JOB_TYPE, RANK_ID, LICENSE_NO)
VALUES('DOC-25-002',NULL,20,'한길동','12345@gmail.com','010-1122-3344','W','20251222','의사','과장','123456');
SELECT * FROM MEDICAL_MRI_FOLDER;
SELECT * FROM MEDICAL_STAFF;
UPDATE MEDICAL_STAFF SET STAFF_ID = 'DOC-25-001' WHERE STAFF_ID = 1;

-- 아직 안 넣음..
INSERT INTO MEDICAL_MRI_FOLDER(PATIENT_ID, DOCTOR_ID, IMAGE_FOLDER_PATH, UPLOAD_DT, TOTAL_SLICES, AI_ANALYSIS_STATUS, AI_MODEL_VERSION)
VALUES('1','DOC-25-001','/home/test/1','2025-12-20','100','PENDING','1.0');


-- 2. 테이블 삭제 (제약조건 무시하고 강제 삭제)
DROP TABLE TUMOR_ANNOTATION CASCADE CONSTRAINTS;
DROP TABLE DIAGNOSIS_REPORT CASCADE CONSTRAINTS;
DROP TABLE MEDICAL_MRI_FOLDER CASCADE CONSTRAINTS;
DROP TABLE GENERAL_MRI_FOLDER CASCADE CONSTRAINTS;
DROP TABLE SYSTEM_LOG CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;
DROP TABLE MEDICAL_STAFF CASCADE CONSTRAINTS;
DROP TABLE INTEGRATED_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;
DROP TABLE MRI_ACCESS_LOG CASCADE CONSTRAINTS;
DROP TABLE GENERAL CASCADE CONSTRAINTS;

-- 삭제 확인 (이 쿼리 결과가 없어야 함)
SELECT table_name FROM user_tables;

SELECT * FROM INTEGRATED_ACCOUNT;


SELECT
    m.MED_MRI_ID          AS medMriId,
    m.IMAGE_FOLDER_PATH   AS fileName,
    m.AI_ANALYSIS_STATUS  AS status,
    TO_CHAR(m.UPLOAD_DT, 'YYYY-MM-DD') AS uploadDt,
    p.PATIENT_NAME        AS patientName,
    p.GENDER              AS gender,
    p.BIRTH_DATE          AS birthDate,
    -- [핵심] 서브쿼리로 '내가 마지막으로 본 시간' 가져오기
    (
        SELECT TO_CHAR(MAX(l.ACCESS_DT), 'YYYY-MM-DD HH24:MI')
        FROM MRI_ACCESS_LOG l
        WHERE l.MED_MRI_ID = m.MED_MRI_ID
          AND l.DOCTOR_ID  = s.STAFF_ID
    ) AS lastCheckTime

FROM MEDICAL_MRI_FOLDER m
         -- 1. 환자 정보 조인
         INNER JOIN PATIENT p ON m.PATIENT_ID = p.PATIENT_ID
    -- 2. 의사 정보 조인 (로그인 ID -> STAFF_ID 변환용)
         INNER JOIN MEDICAL_STAFF s ON m.DOCTOR_ID = s.STAFF_ID
         INNER JOIN INTEGRATED_ACCOUNT a ON s.ACCOUNT_ID = a.ACCOUNT_ID
-- 3. 조건: 로그인한 의사(loginId)가 담당한 MRI만 조회
WHERE a.LOGIN_ID = 'doctor'
-- 4. 정렬: 최근 확인한 환자 우선 (NULL은 뒤로), 그 다음 최신 업로드 순
ORDER BY lastCheckTime DESC NULLS LAST, m.UPLOAD_DT DESC;

SELECT * FROM INTEGRATED_ACCOUNT;
SELECT * FROM PATIENT;
SELECT  * FROM MEDICAL_STAFF;
SELECT * FROM MEDICAL_MRI_FOLDER;
INSERT INTO MEDICAL_MRI_FOLDER (PATIENT_ID, DOCTOR_ID, IMAGE_FOLDER_PATH, AI_ANALYSIS_STATUS, UPLOAD_DT)
VALUES ( '1', 'DOC-25-001', '09e287b1b48a4965bec275866196987f.nii.gz', 'READY', SYSDATE);
INSERT INTO MEDICAL_MRI_FOLDER (PATIENT_ID, DOCTOR_ID, IMAGE_FOLDER_PATH, AI_ANALYSIS_STATUS, UPLOAD_DT)
VALUES ( '1', 'DOC-25-001', '6eaede3dcc92425989a236a9db7e9b9f.nii.gz', 'READY', SYSDATE);
SELECT * FROM MRI_ACCESS_LOG;
INSERT INTO MRI_ACCESS_LOG (MED_MRI_ID, DOCTOR_ID, ACCESS_DT) VALUES (1, 'DOC-25-001', SYSDATE);
SELECT MED_MRI_ID, DOCTOR_ID
FROM MEDICAL_MRI_FOLDER;

/*
SELECT
    m.MED_MRI_ID          AS medMriId,
    p.PATIENT_NAME        AS patientName,
    s.STAFF_ID,
    a.LOGIN_ID,
    -- 로그가 없으면 NULL로 나옴 (행은 사라지지 않음)
    (
        SELECT TO_CHAR(MAX(l.ACCESS_DT), 'YYYY-MM-DD HH24:MI')
        FROM MRI_ACCESS_LOG l
        WHERE l.MED_MRI_ID = m.MED_MRI_ID
          AND l.DOCTOR_ID  = s.STAFF_ID
    ) AS lastCheckTime

FROM MEDICAL_MRI_FOLDER m
         -- 데이터를 확인하기 위해 모두 LEFT JOIN으로 변경
         LEFT JOIN PATIENT p ON m.PATIENT_ID = p.PATIENT_ID
         LEFT JOIN MEDICAL_STAFF s ON m.DOCTOR_ID = s.STAFF_ID
         LEFT JOIN INTEGRATED_ACCOUNT a ON s.ACCOUNT_ID = a.ACCOUNT_ID

-- 일단 특정 의사 필터링을 주석 처리하고 전체를 봅니다.
-- WHERE a.LOGIN_ID = '1'
ORDER BY m.UPLOAD_DT DESC;
*/

commit;
